server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8

spring:
  application:
    name: propertyset

  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

---

spring:
  config:
    activate:
      on-profile: dev
